os: linux
dist: xenial
language: ruby
cache: bundler
rvm:
  - "2.4.0"
services:
  - postgresql
addons:
  apt:
    update: true
bundler_args: --without development
before_install:
  - sudo apt-get -y install unoconv
  - unoconv --version
  - gem install bundler:1.14.6
before_script:
  - cp config/database.travis.yml config/database.yml
  - bin/rake db:test:prepare
env:
  - RAILS_ENV=test
script: bin/rspec
